name: Java CI avec Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build avec Maven
      run: mvn -B package --file pom.xml
      
    - name: Lancer les tests
      run: mvn test
      
    - name: Générer rapport de couverture
      run: mvn jacoco:report